[font]
size = 14.0

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "Dank Mono"
style = "Italic"

[font.normal]
family = "UbuntuMono Nerd Font"

[font.offset]
y = 2

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9

[window.padding]
x = 20
y = 15

[colors]
draw_bold_text_with_bright_colors = true

[general]
import = ["/home/joel/.config/alacritty/alacritty-theme/nightfox.yml"]
